export {
  WATCHLIST_EMPTY_FIXTURE,
  WATCHLIST_ITEMS_FIXTURE,
  WATCHLIST_MAX_ITEMS_FIXTURE,
  WATCHLIST_PARTIAL_DATA_FIXTURE,
  WATCHLIST_SINGLE_ITEM_FIXTURE,
} from "./watchlist-items.fixture";

export {
  WATCHLIST_PARTIAL_VEHICLES_FIXTURE,
  WATCHLIST_VEHICLES_BY_VIN_FIXTURE,
  WATCHLIST_VEHICLES_FIXTURE,
  type WatchlistVehicleFixture,
} from "./watchlist-vehicles.fixture";
